# Generated by Django 4.2.4 on 2024-07-10 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('date_of_birth', models.DateField()),
                ('description', models.TextField()),
                ('age', models.IntegerField()),
                ('place_of_birth', models.CharField(max_length=100)),
                ('nickname', models.CharField(blank=True, max_length=50, null=True)),
                ('jersey_name', models.CharField(max_length=50)),
                ('jersey_number', models.CharField(max_length=50)),
                ('height_cm', models.IntegerField()),
                ('batting_style', models.CharField(max_length=20)),
                ('bowling_style', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=50)),
                ('relationship_status', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='leader_images/')),
                ('facebook', models.CharField(max_length=200)),
                ('linkedin', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
