# Generated by Django 4.2.4 on 2024-07-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='blood',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
