# Generated by Django 4.2.4 on 2024-07-12 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_player_blood'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_video', models.FileField(upload_to='Home/Video/')),
                ('content', models.CharField(blank=True, max_length=100, null=True)),
                ('content1', models.CharField(blank=True, max_length=100, null=True)),
                ('content3', models.CharField(blank=True, max_length=100, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='Home/images')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='Home/images')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='Home/images')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='Home/images')),
            ],
        ),
    ]
