# Generated by Django 4.2.4 on 2024-07-12 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='about_img',
            field=models.ImageField(blank=True, null=True, upload_to='Home/images'),
        ),
        migrations.AlterField(
            model_name='home',
            name='content',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='content1',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='content3',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
