# Generated by Django 4.2.4 on 2024-07-13 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0005_player_instagram_player_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='image',
            field=models.ImageField(upload_to='Players_images/'),
        ),
    ]
